CREATE TABLE points
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status        VARCHAR(255),
    x             VARCHAR(255),
    y             VARCHAR(255),
    r             VARCHAR(255),
    isPointInArea BOOLEAN                                 NOT NULL,
    deltaTime     INTEGER                                 NOT NULL,
    time          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_points PRIMARY KEY (id)
);