/*
 * This file is generated by jOOQ.
 */
package ru.ifmo.se.weblab.jooq.tables.records;


import java.sql.Time;
import java.sql.Timestamp;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import ru.ifmo.se.weblab.jooq.tables.Points;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PointsRecord extends UpdatableRecordImpl<PointsRecord> implements Record8<Long, String, String, String, String, Boolean, Integer, Timestamp> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>points.id</code>.
     */
    public PointsRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>points.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>points.status</code>.
     */
    public PointsRecord setStatus(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>points.status</code>.
     */
    public String getStatus() {
        return (String) get(1);
    }

    /**
     * Setter for <code>points.x</code>.
     */
    public PointsRecord setX(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>points.x</code>.
     */
    public String getX() {
        return (String) get(2);
    }

    /**
     * Setter for <code>points.y</code>.
     */
    public PointsRecord setY(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>points.y</code>.
     */
    public String getY() {
        return (String) get(3);
    }

    /**
     * Setter for <code>points.r</code>.
     */
    public PointsRecord setR(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>points.r</code>.
     */
    public String getR() {
        return (String) get(4);
    }

    /**
     * Setter for <code>points.ispointinarea</code>.
     */
    public PointsRecord setIspointinarea(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>points.ispointinarea</code>.
     */
    public Boolean getIspointinarea() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>points.deltatime</code>.
     */
    public PointsRecord setDeltatime(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>points.deltatime</code>.
     */
    public Integer getDeltatime() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>points.time</code>.
     */
    public PointsRecord setTime(Timestamp value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>points.time</code>.
     */
    public Timestamp getTime() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, String, String, String, Boolean, Integer, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, String, String, String, String, Boolean, Integer, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Points.POINTS.ID;
    }

    @Override
    public Field<String> field2() {
        return Points.POINTS.STATUS;
    }

    @Override
    public Field<String> field3() {
        return Points.POINTS.X;
    }

    @Override
    public Field<String> field4() {
        return Points.POINTS.Y;
    }

    @Override
    public Field<String> field5() {
        return Points.POINTS.R;
    }

    @Override
    public Field<Boolean> field6() {
        return Points.POINTS.ISPOINTINAREA;
    }

    @Override
    public Field<Integer> field7() {
        return Points.POINTS.DELTATIME;
    }

    @Override
    public Field<Timestamp> field8() {
        return Points.POINTS.TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getStatus();
    }

    @Override
    public String component3() {
        return getX();
    }

    @Override
    public String component4() {
        return getY();
    }

    @Override
    public String component5() {
        return getR();
    }

    @Override
    public Boolean component6() {
        return getIspointinarea();
    }

    @Override
    public Integer component7() {
        return getDeltatime();
    }

    @Override
    public Timestamp component8() {
        return getTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getStatus();
    }

    @Override
    public String value3() {
        return getX();
    }

    @Override
    public String value4() {
        return getY();
    }

    @Override
    public String value5() {
        return getR();
    }

    @Override
    public Boolean value6() {
        return getIspointinarea();
    }

    @Override
    public Integer value7() {
        return getDeltatime();
    }

    @Override
    public Timestamp value8() {
        return getTime();
    }

    @Override
    public PointsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public PointsRecord value2(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public PointsRecord value3(String value) {
        setX(value);
        return this;
    }

    @Override
    public PointsRecord value4(String value) {
        setY(value);
        return this;
    }

    @Override
    public PointsRecord value5(String value) {
        setR(value);
        return this;
    }

    @Override
    public PointsRecord value6(Boolean value) {
        setIspointinarea(value);
        return this;
    }

    @Override
    public PointsRecord value7(Integer value) {
        setDeltatime(value);
        return this;
    }

    @Override
    public PointsRecord value8(Timestamp value) {
        setTime(value);
        return this;
    }

    @Override
    public PointsRecord values(Long value1, String value2, String value3, String value4, String value5, Boolean value6, Integer value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PointsRecord
     */
    public PointsRecord() {
        super(Points.POINTS);
    }

    /**
     * Create a detached, initialised PointsRecord
     */
    public PointsRecord(Long id, String status, String x, String y, String r, Boolean ispointinarea, Integer deltatime, Timestamp time) {
        super(Points.POINTS);

        setId(id);
        setStatus(status);
        setX(x);
        setY(y);
        setR(r);
        setIspointinarea(ispointinarea);
        setDeltatime(deltatime);
        setTime(time);
    }
}
