/*
 * This file is generated by jOOQ.
 */
package ru.ifmo.se.weblab.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.ifmo.se.weblab.jooq.DefaultSchema;
import ru.ifmo.se.weblab.jooq.Keys;
import ru.ifmo.se.weblab.jooq.tables.records.PointsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Points extends TableImpl<PointsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>points</code>
     */
    public static final Points POINTS = new Points();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PointsRecord> getRecordType() {
        return PointsRecord.class;
    }

    /**
     * The column <code>points.id</code>.
     */
    public final TableField<PointsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>points.status</code>.
     */
    public final TableField<PointsRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>points.x</code>.
     */
    public final TableField<PointsRecord, String> X = createField(DSL.name("x"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>points.y</code>.
     */
    public final TableField<PointsRecord, String> Y = createField(DSL.name("y"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>points.r</code>.
     */
    public final TableField<PointsRecord, String> R = createField(DSL.name("r"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>points.ispointinarea</code>.
     */
    public final TableField<PointsRecord, Boolean> ISPOINTINAREA = createField(DSL.name("ispointinarea"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>points.deltatime</code>.
     */
    public final TableField<PointsRecord, Integer> DELTATIME = createField(DSL.name("deltatime"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>points.time</code>.
     */
    public final TableField<PointsRecord, Timestamp> TIME = createField(DSL.name("time"), SQLDataType.TIMESTAMP(6), this, "");

    private Points(Name alias, Table<PointsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Points(Name alias, Table<PointsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>points</code> table reference
     */
    public Points(String alias) {
        this(DSL.name(alias), POINTS);
    }

    /**
     * Create an aliased <code>points</code> table reference
     */
    public Points(Name alias) {
        this(alias, POINTS);
    }

    /**
     * Create a <code>points</code> table reference
     */
    public Points() {
        this(DSL.name("points"), null);
    }

    public <O extends Record> Points(Table<O> child, ForeignKey<O, PointsRecord> key) {
        super(child, key, POINTS);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<PointsRecord, Long> getIdentity() {
        return (Identity<PointsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PointsRecord> getPrimaryKey() {
        return Keys.PK_POINTS;
    }

    @Override
    public List<UniqueKey<PointsRecord>> getKeys() {
        return Arrays.<UniqueKey<PointsRecord>>asList(Keys.PK_POINTS);
    }

    @Override
    public Points as(String alias) {
        return new Points(DSL.name(alias), this);
    }

    @Override
    public Points as(Name alias) {
        return new Points(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Points rename(String name) {
        return new Points(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Points rename(Name name) {
        return new Points(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, String, String, String, Boolean, Integer, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
