apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - port: 5672
      name: amqp
      targetPort: 5672
    - port: 15672
      name: management
      targetPort: 15672
  selector:
    app: rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASS
              value: "${RABBITMQ_PASS}"

---
apiVersion: v1
kind: Service
metadata:
  name: api-core
spec:
  type: LoadBalancer
  selector:
    app: api-core
  ports:
    - port: 8001
      targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-core
  template:
    metadata:
      labels:
        app: api-core
    spec:
      containers:
        - name: core-container
          image: safarislava/pc-api-core-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: CLIENT_ID
              value: "${GOOGLE_CLIENT_ID}"
            - name: CLIENT_SECRET
              value: "${GOOGLE_CLIENT_SECRET}"

---
apiVersion: v1
kind: Service
metadata:
  name: api-user
spec:
  type: LoadBalancer
  selector:
    app: api-user
  ports:
    - port: 8002
      targetPort: 8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-user
  template:
    metadata:
      labels:
        app: api-user
    spec:
      containers:
        - name: user-container
          image: safarislava/pc-api-user-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: DB_URL
              value: "${DB_URL}"
            - name: DB_USERNAME
              value: "${DB_USER}"
            - name: DB_PASSWORD
              value: "${DB_PASSWORD}"
            - name: SECRET
              value: "${JWT_SECRET}"

---
apiVersion: v1
kind: Service
metadata:
  name: api-shot
spec:
  type: LoadBalancer
  selector:
    app: api-shot
  ports:
    - port: 8003
      targetPort: 8003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-shot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-shot
  template:
    metadata:
      labels:
        app: api-shot
    spec:
      containers:
        - name: shot-container
          image: safarislava/pc-api-shot-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: DB_URL
              value: "${DB_URL}"
            - name: DB_USERNAME
              value: "${DB_USER}"
            - name: DB_PASSWORD
              value: "${DB_PASSWORD}"
            - name: SECRET
              value: "${JWT_SECRET}"

---
apiVersion: v1
kind: Service
metadata:
  name: api-bff
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  selector:
    app: api-bff
  ports:
    - port: 8004
      targetPort: 8004
      name: http-ws
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-bff
  template:
    metadata:
      labels:
        app: api-bff
    spec:
      containers:
        - name: bff-container
          image: safarislava/pc-api-bff-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8004
          env:
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"