/*
 * This file is generated by jOOQ.
 */
package ru.ifmo.se.weblab.jooq;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.ifmo.se.weblab.jooq.tables.Points;
import ru.ifmo.se.weblab.jooq.tables.records.PointsRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PointsRecord> PK_POINTS = Internal.createUniqueKey(Points.POINTS, DSL.name("pk_points"), new TableField[] { Points.POINTS.ID }, true);
}
