/*
 * This file is generated by jOOQ.
 */
package ru.ifmo.se.weblab.jooq;


import ru.ifmo.se.weblab.jooq.tables.Points;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>points</code>.
     */
    public static final Points POINTS = Points.POINTS;
}
